###
GET http://localhost:3000/actors
Content-Type: application/json
Accept: application/json

###
GET http://localhost:3000/actors/1
Content-Type: application/json
Accept: application/json

###
POST http://localhost:3000/actors
Content-Type: application/json
Accept: application/json

{
    "first_name": "Marco",
    "last_name": "Reynolds"
}

###
PUT http://localhost:3000/actors/1
Content-Type: application/json
Accept: application/json

{
    "first_name": "Lucas",
    "last_name": "Moura"
}

###
DELETE http://localhost:3000/actors/3
Content-Type: application/json
Accept: application/json
